- name: Update repo cache and install chromium
  apt:
    name: chromium-browser
    update_cache: yes
  become: true

- name: Add jellyfin-client.sh script
  synchronize:
    src: jellyfin-client.sh
    dest: /usr/local/bin/jellyfin-client.sh
  become: true

- name: Add jellyfin-client.desktop
  synchronize:
    src: jellyfin-client.desktop
    dest: /etc/xdg/autostart/jellyfin-client.desktop
  become: true

- name: Restart the system
  shell: sleep 2 && shutdown -r now "Ansible-initiated reboot"
  async: 1
  poll: 0
  ignore_errors: true
